### ISSUE TITLE
Suggestions for new terms

### ISSUE THREAD

**Issue by hekl** [NatLibFi/Annif#224]
Is their a possibility to get suggestions for terms that are important in a document or a set of documents, but that are not present in the supported vocabulary?

**Comment by osma** [comment]
Thanks, it's a great suggestion, but in its current form Annif is quite focused on recognizing existing concepts from a predefined vocabulary, not suggesting new ones to be added to the vocabulary.

I think this could be added to the Maui backend, because it is based on a lexical approach and has to compare terms in the vocabulary to terms that appear in the text. For example the MauiService REST API could have a method for suggesting new terms/concepts. I seem to remember that such tools have previously been built over Maui's predecessor Kea (or Kea++).

**Comment by hekl** [comment]
I have used Rake, and it can suggest the most interesting keywords in a document, but this did not connect to a vocabulary.

**Comment by osma** [comment]
I wasn't avare of RAKE and that there's a Python implementation available, thanks for the hint. This could be a valuable addition for the future, so I'm reopening the issue.

**Comment by hekl** [comment]
Of course both MAUI and Rake have been used by [Alyona Medelyan](https://www.airpair.com/nlp/keyword-extraction-tutorial). I found Rake working quite good, considering its elementary setup.

**Comment by osma** [comment]
Superseded by #566
