### ISSUE TITLE
Fasttext with Gunicorn problem

### ISSUE THREAD

**Issue by TommiRTVA** [NatLibFi/Annif#328]
I am using Annif with Docker, and my OS is Windows 10. I am trying to launch Annif, Maui, Gunicorn and NGINX services with docker-compose.yml. There seems to be some issue concerning fasttext project and Gunicorn startup; Gunicorn cannot initialize my fasttext project. It looks for the vectorizer file:

Couldn't initialize project 'yso-fasttext-fi': vectorizer file 'data/projects/yso-fasttext-fi/vectorizer' not found
gunicorn_server_1  | [2019-09-12 12:09:06 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:241)
gunicorn_server_1  | [2019-09-12 12:09:08 +0000] [245] [INFO] Booting worker with pid: 245

This error message keeps looping with different PIDs.

Project configuration:
[yso-fasttext-fi]
name=YSO fastText Finnish
language=fi
backend=fasttext
analyzer=snowball(finnish)
dim=430
lr=0.74
epoch=75
minn=4
maxn=7
minCount=3
loss=hs
limit=1000
chunksize=24
vocab=yso-fi

Files in the data-folder:
![kuva](https://user-images.githubusercontent.com/47444068/64783143-b407b180-d56f-11e9-9193-12afb3ea600b.png)

**Comment by TommiRTVA** [comment]
Seems like this is solved in latest version, fasttext works with gunicorn.

**Comment by osma** [comment]
Sorry for not reacting earlier. It seems to me that you had configured several tfidf projects without actually training them - thus they don't have vectorizers (which are created during training).

When running as a WSGI service (e.g. under gunicorn), all projects are initialized and vectorizers are loaded for the projects that require them (tfidf and omikuji need them, other types of backends don't). So basically you can't start up gunicorn if you've defined projects that you haven't also trained. 

This could be seen as a weakness - maybe it would be possible to be more robust and allow the WSGI service to start up even when some projects cannot be initialized. Some similar ideas are listed in issue #329.

BTW the spurious "analyzer setting is missing" errors that you also saw were fixed in release 0.45 (PR #369).

In any case I'm closing this as your immediate problem was solved. Feel free to open another issue if you still have problems.
