### ISSUE TITLE
Parallelized eval of nn_ensemble projects hangs

### ISSUE THREAD

**Issue by juhoinkinen** [NatLibFi/Annif#453]
When running evaluations for new models with four parallel jobs I noticed that evaluation of nn_ensemble projects never finished. Without multiprocessing there was no problem. 

Minimal example:
```
# projects.cfg:
[arch-fasttext]
name=FastText
language=fi
backend=fasttext
limit=100
vocab=arch
analyzer=snowball(finnish)

[arch-nn]
name=YSO NN ensemble Finnish
language=fi
backend=nn_ensemble
sources=arch-fasttext
limit=100
vocab=arch
nodes=100
dropout_rate=0.2
epochs=2

# Testing:
annif loadvoc arch-fasttext tests/corpora/archaeology/subjects.tsv
annif train arch-fasttext tests/corpora/archaeology/documents.tsv
annif train arch-nn tests/corpora/archaeology/fulltext/
time annif eval arch-nn tests/corpora/archaeology/documents.tsv --jobs 1  # finishes in 3 min
time annif eval arch-nn tests/corpora/archaeology/documents.tsv --jobs 2  # won't finish
```

This seems to be a common problem, there's many search results for "python multiprocess hangs when calling a tensorflow model". The problem occurs at least with TF versions 2.2.0 and 2.3.1. A quick fix could be to throw a `NotSupportedException` instead of indefinite freeze. Parallelized eval was not promised to work with nn_ensemble when the feature was implemented in #418.

**Comment by osma** [comment]
Thanks for the report and the minimal test case, this is very useful analysis.
I labelled this as a bug because the command just silently hangs forever.

**Comment by osma** [comment]
I took a closer look - the problem is the backend initialization on this line: https://github.com/NatLibFi/Annif/blob/master/annif/cli.py#L365

This is done just before the workers are started in forked processes. This way the initialization (e.g. loading models from disk into memory) has to be done just once and the workers can then make use of them without having to load them anymore. But TensorFlow doesn't like this - maybe it uses shared memory that doesn't behave well after forking.

Commenting out this line makes the NN ensemble work in parallel - since the initialization of projects (not just the ensemble, but also the projects it uses as sources) is delayed and happens within each worker process. The downside is that this takes longer and uses more memory.

I'm now trying to think of an elegant way of delaying the initialization of the TensorFlow/Keras model while still initializing e.g. the source projects.
