### ISSUE TITLE
Improve performance of updating an existing vocabulary

### ISSUE THREAD

**Issue by niko2342** [NatLibFi/Annif#516]
Hi,

to update an existing vocabulary with more than 1.3 million of concepts takes hours, because the existings graph is loaded and each triple is checked. I think it would be an good improvement to add an `--overwrite` or `--force` parameter to the loadvoc command. After the existing graph is deleted the loadvoc command behaves as it would load a new vocabulary.

What do you think?

Kind regards
Nico

**Comment by osma** [comment]
Thanks for the suggestion!

How long does it take for you to
1) load the vocabulary the first time?
2) load it the second time?

I'm curious because there shouldn't be a big difference. Updating is otherwise the same, but Annif attempts to preserve subject ID numbers during a vocabulary update. It's not checking every triple. But of course the new vocabulary file has to be parsed, and also reserialized if it isn't in Turtle format already. Using a Turtle file (`.ttl`) is faster than other RDF serializations, since then it can just be copied.

**Comment by niko2342** [comment]
Loading the vocabulary the first takes  ~12 minutes; updating the vocabulary (same command, same data) takes ~10 hours 38 minutes. The values are measured on a server with 16 CPUs running Ubuntu 18.04.4 LTS, 32 GB Memory, 640 GB RAM. The vocabulary contains:

- 1,303,546 concepts
- 1,303,546 pref labels
- 2,189,261 alt labels
- 1,012,172 hidden labels
- 573,315 broader relations
- 2,232,872 related relations

The vocabulary was serialized in turtle format using rdflib (python).

**Comment by osma** [comment]
Thank you for the information - whoa, that's a pretty huge difference! I think there must be something in the vocabulary update process that makes it unnecessarily slow in your case. That's something to fix, potentially.

In addition, it could be useful for the `loadvoc` command to have a parameter such as `--replace`, `--overwrite` or `--force`, like you suggested above. There are situations where it makes sense to start from a clean slate.

**Comment by osma** [comment]
I found the problem and fixed it in PR #525, which was just merged to the `master` branch. Updating the vocabulary is now as fast as loading it the first time.

I will open a separate issue about the parameter to force reloading the vocabulary.
