### ISSUE TITLE
Avoid using pytest-flake8, run flake8 separately instead

### ISSUE THREAD

**Issue by osma** [NatLibFi/Annif#599]
We are currently using pytest-flake8, which runs flake8 code style checks within pytest. But it has turned out to be fragile (see PR #598 and https://github.com/tholo/pytest-flake8/issues/87) and many projects are switching to a setup where flake8 is run separately (see https://github.com/pypa/pep517/pull/147 , https://github.com/pytest-dev/pytest/issues/9217#issuecomment-965144375, https://github.com/miketheman/pytest-socket/issues/82 )

We should also consider doing this. At the moment it is not possible to use the recently released flake8 version 5 because it's not compatible with pytest-flake8 1.1.1, so we have for now pinned flake8 to version 4 in #598, but this is not a good long term solution.

**Comment by juhoinkinen** [comment]
Now (since #640 and #641) we have a CI/CD job for Black and isort lint checks the flake8 check could be easily added to that job.

The instruction for the [precommit hook](https://github.com/NatLibFi/Annif/blob/master/CONTRIBUTING.md#code-style) already includes flake8, so running flake8 within pytest is redundant, so pytest-flake8 plugin can be just removed and flake8 upgraded to latest version.
